component: scf # (必选) 组件名称，在该实例中为scf
name: april-scf # 必选) 组件实例名称.
org: serverless # (可选) 用于记录组织信息，默认值为您的腾讯云账户 appid
app: AprilApp # (可选) 用于记录组织信息. 默认与name相同.
stage: dev # (可选) 用于区分环境信息，默认值是 dev

inputs:
  name: april-func # 云函数名称
  src: ./
  handler: index.main_handler 
  runtime: Nodejs8.9 
  region: ap-guangzhou # 函数所在区域
  description: My Serverless Function
  memorySize: 128 # 内存大小，单位MB
  timeout: 20 # 超时时间，单位秒
  
  events: # 触发器
    - cos: # cos触发器
        name: ${output:${stage}:${app}:april-test.cosOrigin}
        parameters:
          bucket: ${output:${stage}:${app}:april-test.cosOrigin}
          events: 'cos:ObjectCreated:*'
          enable: true