name: mytest-demo
author: april
org: serverless
description: My first template
keywords: scf, cos, nodejs
repo: https://github.com/Jiachen0417/tencent-serverless-demo/tree/master/april-demo
readme: https://github.com/Jiachen0417/tencent-serverless-demo/blob/master/README.md
license: MIT
src:
  src: ./
  exclude:
    - .env
    - '.git/**'
    - serverless.yml
    - '**/node_modules'
    - '**/package-lock.json'